// Code generated by "stringer -type=AtType -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AT_TOP_LEFT-0]
	_ = x[AT_BOTTOM_LEFT-1]
	_ = x[AT_BOTTOM_CENTER-2]
	_ = x[AT_CENTER-3]
}

const _AtType_name = "AT_TOP_LEFTAT_BOTTOM_LEFTAT_BOTTOM_CENTERAT_CENTER"

var _AtType_index = [...]uint8{0, 11, 25, 41, 50}

func (i AtType) String() string {
	if i < 0 || i >= AtType(len(_AtType_index)-1) {
		return "AtType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AtType_name[_AtType_index[i]:_AtType_index[i+1]]
}
