// Code generated by "stringer -type=BlockType -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BLOCK_TRAP-0]
	_ = x[BLOCK_WALL-1]
	_ = x[BLOCK_FLOOR-2]
	_ = x[BLOCK_EXIT-3]
}

const _BlockType_name = "BLOCK_TRAPBLOCK_WALLBLOCK_FLOORBLOCK_EXIT"

var _BlockType_index = [...]uint8{0, 10, 20, 31, 41}

func (i BlockType) String() string {
	if i < 0 || i >= BlockType(len(_BlockType_index)-1) {
		return "BlockType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlockType_name[_BlockType_index[i]:_BlockType_index[i+1]]
}
