// Code generated by "stringer -type=FlipType -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FLIP_NONE-0]
	_ = x[FLIP_H-1]
	_ = x[FLIP_V-2]
}

const _FlipType_name = "FLIP_NONEFLIP_HFLIP_V"

var _FlipType_index = [...]uint8{0, 9, 15, 21}

func (i FlipType) String() string {
	if i < 0 || i >= FlipType(len(_FlipType_index)-1) {
		return "FlipType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlipType_name[_FlipType_index[i]:_FlipType_index[i+1]]
}
