package game

// generated
const (
	RES_WALL_TOP_LEFT                 = 0
	RES_WALL_TOP_MID                  = 1
	RES_WALL_TOP_RIGHT                = 2
	RES_WALL_LEFT                     = 3
	RES_WALL_MID                      = 4
	RES_WALL_RIGHT                    = 5
	RES_WALL_FOUNTAIN_TOP             = 6
	RES_WALL_FOUNTAIN_MID_RED_ANIM    = 7
	RES_WALL_FOUNTAIN_BASIN_RED_ANIM  = 8
	RES_WALL_FOUNTAIN_MID_BLUE_ANIM   = 9
	RES_WALL_FOUNTAIN_BASIN_BLUE_ANIM = 10
	RES_WALL_HOLE_1                   = 11
	RES_WALL_HOLE_2                   = 12
	RES_WALL_BANNER_RED               = 13
	RES_WALL_BANNER_BLUE              = 14
	RES_WALL_BANNER_GREEN             = 15
	RES_WALL_BANNER_YELLOW            = 16
	RES_COLUMN_TOP                    = 17
	RES_COLUMN_MID                    = 18
	RES_COULMN_BASE                   = 19
	RES_WALL_COLUMN_TOP               = 20
	RES_WALL_COLUMN_MID               = 21
	RES_WALL_COULMN_BASE              = 22
	RES_WALL_GOO                      = 23
	RES_WALL_GOO_BASE                 = 24
	RES_FLOOR_1                       = 25
	RES_FLOOR_2                       = 26
	RES_FLOOR_3                       = 27
	RES_FLOOR_4                       = 28
	RES_FLOOR_5                       = 29
	RES_FLOOR_6                       = 30
	RES_FLOOR_7                       = 31
	RES_FLOOR_8                       = 32
	RES_FLOOR_LADDER                  = 33
	RES_FLOOR_SPIKES_ANIM             = 34
	RES_WALL_SIDE_TOP_LEFT            = 35
	RES_WALL_SIDE_TOP_RIGHT           = 36
	RES_WALL_SIDE_MID_LEFT            = 37
	RES_WALL_SIDE_MID_RIGHT           = 38
	RES_WALL_SIDE_FRONT_LEFT          = 39
	RES_WALL_SIDE_FRONT_RIGHT         = 40
	RES_WALL_CORNER_TOP_LEFT          = 41
	RES_WALL_CORNER_TOP_RIGHT         = 42
	RES_WALL_CORNER_LEFT              = 43
	RES_WALL_CORNER_RIGHT             = 44
	RES_WALL_CORNER_BOTTOM_LEFT       = 45
	RES_WALL_CORNER_BOTTOM_RIGHT      = 46
	RES_WALL_CORNER_FRONT_LEFT        = 47
	RES_WALL_CORNER_FRONT_RIGHT       = 48
	RES_WALL_INNER_CORNER_L_TOP_LEFT  = 49
	RES_WALL_INNER_CORNER_L_TOP_RIGTH = 50
	RES_WALL_INNER_CORNER_MID_LEFT    = 51
	RES_WALL_INNER_CORNER_MID_RIGTH   = 52
	RES_WALL_INNER_CORNER_T_TOP_LEFT  = 53
	RES_WALL_INNER_CORNER_T_TOP_RIGTH = 54
	RES_EDGE                          = 55
	RES_HOLE                          = 56
	RES_DOORS_ALL                     = 57
	RES_DOORS_FRAME_LEFT              = 58
	RES_DOORS_FRAME_TOP               = 59
	RES_DOORS_FRAME_RIGH              = 60
	RES_DOORS_LEAF_CLOSED             = 61
	RES_DOORS_LEAF_OPEN               = 62
	RES_CHEST_EMPTY_OPEN_ANIM         = 63
	RES_CHEST_FULL_OPEN_ANIM          = 64
	RES_CHEST_MIMIC_OPEN_ANIM         = 65
	RES_FLASK_BIG_RED                 = 66
	RES_FLASK_BIG_BLUE                = 67
	RES_FLASK_BIG_GREEN               = 68
	RES_FLASK_BIG_YELLOW              = 69
	RES_FLASK_RED                     = 70
	RES_FLASK_BLUE                    = 71
	RES_FLASK_GREEN                   = 72
	RES_FLASK_YELLOW                  = 73
	RES_SKULL                         = 74
	RES_CRATE                         = 75
	RES_COIN_ANIM                     = 76
	RES_UI_HEART_FULL                 = 77
	RES_UI_HEART_HALF                 = 78
	RES_UI_HEART_EMPTY                = 79
	RES_WEAPON_KNIFE                  = 80
	RES_WEAPON_RUSTY_SWORD            = 81
	RES_WEAPON_REGULAR_SWORD          = 82
	RES_WEAPON_RED_GEM_SWORD          = 83
	RES_WEAPON_BIG_HAMMER             = 84
	RES_WEAPON_HAMMER                 = 85
	RES_WEAPON_BATON_WITH_SPIKES      = 86
	RES_WEAPON_MACE                   = 87
	RES_WEAPON_KATANA                 = 88
	RES_WEAPON_SAW_SWORD              = 89
	RES_WEAPON_ANIME_SWORD            = 90
	RES_WEAPON_AXE                    = 91
	RES_WEAPON_MACHETE                = 92
	RES_WEAPON_CLEAVER                = 93
	RES_WEAPON_DUEL_SWORD             = 94
	RES_WEAPON_KNIGHT_SWORD           = 95
	RES_WEAPON_GOLDEN_SWORD           = 96
	RES_WEAPON_LAVISH_SWORD           = 97
	RES_WEAPON_RED_MAGIC_STAFF        = 98
	RES_WEAPON_GREEN_MAGIC_STAFF      = 99
	RES_WEAPON_SPEAR                  = 100
	RES_TINY_ZOMBIE                   = 102
	RES_GOBLIN                        = 104
	RES_IMP                           = 106
	RES_SKELET                        = 108
	RES_MUDDY                         = 110
	RES_SWAMPY                        = 112
	RES_ZOMBIE                        = 114
	RES_ICE_ZOMBIE                    = 116
	RES_MASKED_ORC                    = 118
	RES_ORC_WARRIOR                   = 120
	RES_ORC_SHAMAN                    = 122
	RES_NECROMANCER                   = 124
	RES_WOGOL                         = 126
	RES_CHORT                         = 128
	RES_BIG_ZOMBIE                    = 130
	RES_ORGRE                         = 132
	RES_BIG_DEMON                     = 134
	RES_ELF_F_IDLE_ANIM               = 135
	RES_ELF_F_RUN_ANIM                = 136
	RES_ELF_F_HIT_ANIM                = 137
	RES_ELF_M                         = 139
	RES_ELF_M_HIT_ANIM                = 140
	RES_KNIGHT_F_IDLE_ANIM            = 141
	RES_KNIGHT_F_RUN_ANIM             = 142
	RES_KNIGHT_F_HIT_ANIM             = 143
	RES_KNIGHT_M                      = 145
	RES_WIZZARD_F_IDLE_ANIM           = 147
	RES_WIZZARD_F_RUN_ANIM            = 148
	RES_WIZZARD_F_HIT_ANIM            = 149
	RES_WIZZARD_M                     = 151
	RES_WIZZARD_M_HIT_ANIM            = 152
	RES_LIZARD_F_IDLE_ANIM            = 153
	RES_LIZARD_F_RUN_ANIM             = 154
	RES_LIZARD_F_HIT_ANIM             = 155
	RES_LIZARD_M_IDLE_ANIM            = 156
	RES_LIZARD_M_RUN_ANIM             = 157
	RES_LIZARD_M_HIT_ANIM             = 158
	RES_ZIGGY_M                       = 160
	RES_ZIGGY_M_HIT_ANIM              = 161
	RES_GREEN_HOOD_SKEL               = 163
	RES_FIREBALL_EXPLOSION1           = 164
	RES_HALO_EXPLOSION1               = 165
	RES_HALO_EXPLOSION2               = 166
	RES_FIREBALL                      = 167
	RES_FLOOR_SPIKE_DISABLED          = 168
	RES_FLOOR_SPIKE_ENABLED           = 169
	RES_FLOOR_SPIKE_OUT_ANI           = 170
	RES_FLOOR_SPIKE_IN_ANI            = 171
	RES_FLOOR_EXIT                    = 172
	RES_HPMED                         = 173
	RES_SWORDFX                       = 174
	RES_CLAWFX                        = 175
	RES_SHINE                         = 176
	RES_THUNDER                       = 177
	RES_BLOODBOUND                    = 178
	RES_ARROW                         = 179
	RES_EXPLOSION_2                   = 180
	RES_CLAWFX2                       = 181
	RES_AXE                           = 182
	RES_CROSS_HIT                     = 183
	RES_BLOOD1                        = 184
	RES_BLOOD2                        = 185
	RES_BLOOD3                        = 186
	RES_BLOOD4                        = 187
	RES_SOLIDFX                       = 188
	RES_SOLID_GREENFX                 = 189
	RES_ICEPICK                       = 190
	RES_ICESHATTER                    = 191
	RES_ICE                           = 192
	RES_HOLYSWORD                     = 193
	RES_FIRESWORD                     = 194
	RES_ICESWORD                      = 195
	RES_GRASSSWORD                    = 196
	RES_IRONSWORD                     = 197
	RES_HOLY_SHIELD                   = 198
	RES_GOLDEN_CROSS_HIT              = 199
	RES_SLIDER                        = 200
	RES_BLUEBAR                       = 201
	RES_TITLE                         = 202
	RES_PURPLE_BALL                   = 203
	RES_PURPLE_EXP                    = 204
	RES_PURPLE_STAFF                  = 205
	RES_THUNDER_STAFF                 = 206
	RES_THUNDER_YELLOW                = 207
	RES_ATTACK_UP                     = 208
	RES_BOW                           = 209
	RES_PURPLE_FIRE_BALL              = 210
	RES_STARFIELD                     = 211
	// RES_TINY_ZOMBIE_IDLE_ANIM         = 101
	// RES_GOBLIN_IDLE_ANIM = 103
	// RES_IMP_IDLE_ANIM    = 105
	// RES_SKELET_IDLE_ANIM = 107
	// RES_MUDDY_IDLE_ANIM               = 109
	// RES_SWAMPY_IDLE_ANIM = 111
	// RES_ZOMBIE_IDLE_ANIM              = 113
	// RES_ICE_ZOMBIE_IDLE_ANIM  = 115
	// RES_MASKED_ORC_IDLE_ANIM  = 117
	// RES_ORC_WARRIOR_IDLE_ANIM = 119
	// RES_ORC_SHAMAN_IDLE_ANIM  = 121
	// RES_NECROMANCER_IDLE_ANIM = 123
	// RES_WOGOL_IDLE_ANIM = 125
	// RES_CHORT_IDLE_ANIM               = 127
	// RES_BIG_ZOMBIE_IDLE_ANIM = 129
	// RES_OGRE_IDLE_ANIM      = 131
	// RES_BIG_DEMON_IDLE_ANIM = 133
	// RES_ELF_M_IDLE_ANIM      = 138
	// RES_KNIGHT_M             = 144 // _IDLE_ANIM
	// RES_KNIGHT_M_HIT_ANIM             = 146
	// RES_WIZZARD_M_IDLE_ANIM  = 150
	// RES_ZIGGY_M_IDLE_ANIM    = 159
	// RES_GREEN_SKEL_IDLE      = 162
)
